### PR TITLE
Update ion_auth.postgre.sql

### PR DESCRIPTION
**Pull request by cjonstrup**
When creating new groups you get a error.

current value of the groups_id_seq sequence is still 1.

### CODE REVIEW

**Comment by benedmunds** [comment]
This shouldnt happen with a clean DB since these are SERIALs.

**Comment by cjonstrup** [comment]
If you use ion_auth.postgre.sql with the 2 default groups it fails when creating new groups.

**Comment by benedmunds** [comment]
What version of PG are you running?

This is what I see:

```

Ben@ayr ~> postgres --version
postgres (PostgreSQL) 9.4.5

Ben@ayr ~> createdb 'ion_postgres_test'

Ben@ayr ~> psql -U postgres ion_postgres_test < ion_auth.postgre.sql
CREATE TABLE
CREATE TABLE
CREATE TABLE
INSERT 0 2
INSERT 0 1
INSERT 0 2
CREATE TABLE
```

**Comment by cjonstrup** [comment]
The sql script is fine. If you run the application and try to create a new group you get a error.

**Comment by benedmunds** [comment]
Sounds like maybe your serials didn't generate correctly? What error are you getting?

**Comment by benedmunds** [comment]
Closing due to inactivity. Please comment if this is stil an issue.

**Pull request closed without merging**
