### PR TITLE
fixbug ci4 filterData

### PR DESCRIPTION
**Pull request by junglaCODE**
Send changes in the function filterData related with issue #1528 .   I hope it is helpful for this great library :)

### CODE REVIEW

**Comment by benedmunds** [comment]
There's something wrong with this PR.  It should only have the one commit, this is showing 55.  Did you branch and pull the latest to your base branch?  And are you merging with the current target branch?

**Comment by junglaCODE** [comment]
this branch generated merge with conflicts, It was weird, but I ignored it. What I can do ?

**Comment by benedmunds** [comment]
The easiest way is to probably pull down the 4 branch to a new branch, cherry pick your commit, then submit a new PR

**Comment by junglaCODE** [comment]
ok. working in issue. Thanks

**Pull request closed without merging**
