### PR TITLE
Update auth.php

### PR DESCRIPTION
**Pull request by ft23**
anybody forgot password :)

### CODE REVIEW

**Comment by benedmunds** [comment]
Does the field name in the form match this? I think this was intentional due to the field name being email if I remember correctly.

Might be best to just switch it all to Identity?

**Comment by Tjoosten** [comment]
@ft23 can u plz fix the merge issues?

CC @benedmunds

**Comment by avenirer** [comment]
@benedmunds I don't think this pull request is needed anymore. As I remember, everything works ok with the library

**Comment by benedmunds** [comment]
Thanks!

**Pull request closed without merging**
