### PR TITLE
Languages/sinhala

### PR DESCRIPTION
**Pull request by rajitha-bandara**
Added Sinhala translations.

### CODE REVIEW

**Comment by benedmunds** [comment]
This is committing a bunch of non-language related stuff.

**Comment by rajitha-bandara** [comment]
Sorry, I didn't get your point. I just translated Ion Auth language files to a new language. Have I missed something?
 This is my first contrib. action. So can be..

**Comment by Tjoosten** [comment]
What he means is that you try to merge a buNch of non language stuff into master. 

I think that it's better that you only send a PR for the language files.

**Comment by rajitha-bandara** [comment]
My mistake. Selected wrong base branch.

**Pull request closed without merging**
