### PR TITLE
destroy and regenerate in PHP

### PR DESCRIPTION
**Pull request by avenirer**
destroy session and regenerate session directly in PHP

### CODE REVIEW

**Comment by benedmunds** [comment]
Whats the reason for bypassing CI?

**Comment by benedmunds** [comment]
and does this work with something like CI's DB session handling.

**Comment by avenirer** [comment]
At least regarding CI 3, sess_regenerate() is actually an alias for the PHP native function session_regenerate_id (as I see in the manual). Regarding the sess_destroy() method, looking inside the version 2.x's session library I see that is actually calling session_destroy().

I actually do have a question regarding the recreation of the session: Why do you need to recreate it manually? The session is created again automatically when the Session library is loaded. Or am I wrong? I would remove that part entirely.

**Comment by benedmunds** [comment]
If I remember correct regenerating it was so it would go ahead and clear everything, otherwise it was taking one additional load before it cleared and there could be leftover data.  It's been awhile since I wrong that though so I could be wrong.

**Pull request closed without merging**
