### PR TITLE
Improved white-space, formatting and PHPDoc/comments

### PR DESCRIPTION
**Pull request by aphofstede**
Changed to be more consistent with either the rest of the lib or CI itself.
Note: Added an @deprecated tag to `_prepare_ip()`, `is_time_locked_out()` and `get_last_attempt_time()`, since the comments already said as much.

### CODE REVIEW

**Comment by benedmunds** [comment]
Really great update here, thanks for this.

One item, the doc blocks for the user_ids should have float as a possible type as well shouldnt they?

**Comment by aphofstede** [comment]
Yes, I guess you're right. Although it's a bit silly, if they get cast to float anyway you can also pass them in. I'll update the PR.

**Comment by aphofstede** [comment]
Done. Note that group/user ID is not cast to float everywhere; was that intentional? I don't use bigint myself.

**Comment by benedmunds** [comment]
Shouldn’t really matter as long as it’s casted before it gets to the DB, and even then the DB will catch it but I try to avoid that.

Thanks!

**Comment by benedmunds** [comment]
Merged 🎉

**Pull request merged**
