### PR TITLE
add table for users_last_logins, then also on update column of users

### PR DESCRIPTION
**Pull request by lloricode**
if this is ok, i will also PR for getting all last_login by current user or as parameter of user(s)

### CODE REVIEW

**Comment by avenirer** [comment]
Why this?

**Comment by lloricode** [comment]
@avenirer  to see the all last login in all users?. because i want to monitor all last logins

**Comment by avenirer** [comment]
I don't think this in needed. You can do this inside any controller by reading the session variable last login.

**Comment by lloricode** [comment]
@avenirer , but not on session we want to get the last login, we just want to get the all from the past login?

**Comment by lloricode** [comment]
because once user login again, it will override the time() in users row, so saving in other table is the other way,

**Comment by avenirer** [comment]
Yes. On every successful login you can do it in your own flow.

**Comment by benedmunds** [comment]
Closing, this isn't something we'd want to add to the core.

**Comment by lloricode** [comment]
@benedmunds , ok sir

**Pull request closed without merging**
