### PR TITLE
edit only group description

### PR DESCRIPTION
**Pull request by lloricode**
allowing edit all description,but not all name of groups,

the parameter will be is the ID and Description. while the name set to FALSE to ignore update on name.

```php
          //after validation input
	   $group_update = $this->ion_auth->update_group(
                $id, FALSE, $this->input->post('description', TRUE)
         );

```

### CODE REVIEW

**Comment by benedmunds** [comment]
I'm not sure I follow, can you explain the need for this and then the solution you've implemented here please.

**Comment by lloricode** [comment]
hi @benedmunds,

admins can modify all description only even `admin`'s description, not include all `name`.

**Comment by benedmunds** [comment]
Why?

**Comment by lloricode** [comment]
@benedmunds , in my case, the description of current user_group's is in top.
screenshot at 2017-04-16 09-26-52

so admin can rename it.
hmm is this ok?

**Comment by benedmunds** [comment]
There's no probably with the admin renaming groups at a library level.

If you need to stop that from happening in your app you should do it in your controller.

**Comment by lloricode** [comment]
@benedmunds hhmm ok sir,

**Pull request closed without merging**
