### PR TITLE
Update for Ion auth Model

### PR DESCRIPTION
**Pull request by Premgupta01**
just added code  for check Old and New Password should not be same

### CODE REVIEW

**Comment by benedmunds** [comment]
Couple bits of feedback.

1. Can you remove the whitespace updates that arent related to this change

2. Can you remove the comment update are arent related to this change

3. Make the new matches old error be optional based on config for backwards compatibility.  Default it to false so existing installs don't change.

**Comment by lloricode** [comment]
@Premgupta01 its too difficult to review where is the changes

**Comment by Premgupta01** [comment]
I have written a comment in ion model file and comment is "// just added code given below for check Old and New Password should not be same"

You can easily find out this

**Comment by Premgupta01** [comment]
@benedmunds 

Thanks for reviewing code, I am naive in Codeigniter, So can you please guide me here 

1. Make the new matches old error be optional based on config for backwards compatibility. Default it to false so existing installs don't change.

Do I need to add this change to the latest code?

**Comment by lloricode** [comment]
maybe, just push some related to this PR, to easily check by the owner. its good you format the codes, but, it may cause some trouble if there accidentally change without knowing.

**Comment by Premgupta01** [comment]
okay, @lloricode I am naive and trying to improve my asset with the help of you and others,
Thanks for letting me know So can you please guide me How to add new code to anyone's existing Code.

**Comment by lloricode** [comment]
@benedmunds said that you can or need add a additional config, to set if where need to check if password is same on old. then make it optional so the other using with this library will not break there code if ever merge this PR

**Comment by Premgupta01** [comment]
Yes, I have added it to the config file for display Error Message.

**Comment by benedmunds** [comment]
Closing this due to age.  @Premgupta01 if you want to submit a new PR with *only* the one change you are suggesting and without all the comment and whitespace changes I'll be happy to consider it.  Thanks!

**Pull request closed without merging**
