### PR TITLE
Update Ion_auth_model.php

### PR DESCRIPTION
**Pull request by CharbelJ**
You should not be able to delete yourself if your are the current logged in user.

### CODE REVIEW

**Comment by benedmunds** [comment]
Hey,

For for this but currently there's code in the example controller to prevent this.  I don't think it's something we want to stop at the model level because there are valid use cases where a user should be able to delete themselves.  

For example, in the case of "delete my account and all my data" the user should be able to delete their account and then be logged out afterwards.  Which is really something that should be handled at the controller level.

**Comment by CharbelJ** [comment]
So I should be checking if a user ir currently logged in and deleting themselves on the controller level yeah?

**Comment by benedmunds** [comment]
Hmm I thought there was an example of this in the example controller but there's not..

Yea you'd want to do this in your controller.

**Comment by CharbelJ** [comment]
Thanks a lot man!

**Comment by CharbelJ** [comment]
Would you please show me an example how to handle it in the controller?

**Comment by benedmunds** [comment]
I imagine you have a delete method in your controller or something similar..  If so it'd be something like this:

`
function delete ($id) {
    if ($this->ion_auth->user()->row()->id == $id) {
       show_error('You can not delete yourself');
    }

  .//rest of your logic
`

You'll want to update it to use your validation or whatever you're doing to return errors.

**Comment by CharbelJ** [comment]
Perfect just wanted to see if I was on the right track and it turned I was! Thanks a lot man! Really appreciate it!

**Comment by benedmunds** [comment]
No problem, take care!

**Pull request closed without merging**
