### PR TITLE
Pagination on users() function

### PR DESCRIPTION
**Pull request by AsoStrife**
Is it possible to implement a pagination with $limit and $offset on $this->ion_auth->users()?
Having complete users list is not useful if there more than 50 user.

### CODE REVIEW

**Comment by benedmunds** [comment]
Yea I’d like that.  Looks like you may have opened the PR against the wrong
branch though?

-Ben Edmunds

On July 31, 2016 at 1:04:29 PM, Andrea (notifications@github.com) wrote:

Is it possible to implement a pagination with $limit and $offset on
$this->ion_auth->users()?

## Having complete users list is not useful if there more than 50 user.

You can view, comment on, or merge this pull request online at:

  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970
Commit Summary
- Update ion_auth_lang.php
- Merge pull request #736 from avenirer/patch-4
- allow $this->ion_auth->users() to accept group name
- Update ion_auth_model.php
- Merge pull request #740 from avenirer/patch-5
- no more need for "driver" for CI3
- Merge pull request #745 from avenirer/patch-6
- update manual for users() method
- Mentioning of create_user() and update_user() methods
- Update index.html
- Updated userguide
- Merged in PR 748
- Merge branch 'avenirer-patch-6' into 2
- Merge pull request #749 from avenirer/patch-7
- restrict change of name of the admin group
- restrict change of name of the admin group
- set reason in the error and add language items
- Merge pull request #750 from marcelod/2
- Changed forgotten_password method to use model identity column
- Merge pull request #751 from paulcanning/2
- some error
- Merge pull request #753 from avenirer/patch-8
- updated Turkish language file
- updated reset password method on success
- Merge pull request #755 from ozdemirburak/2
- Delete duplicated stuff in docs
- Merge pull request #756 from gadelat/patch-1
- Update index.html
- Merge pull request #761 from sparky672/patch-3
- Update index.html
- Merge pull request #762 from sparky672/patch-4
- \- Added comment on "README.md" for better understanding of beginners.
- Merge pull request #763 from ronaldaraujo/2
- Added clear_messages and clear_errors methods to the model. Added
  clearing of deactivate message during registration process.
- Updated the dutch language file
- Updated the dutch language file
- Updated the dutch language file
- Merge pull request #771 from DiederikLascaris/2
- unambigous order_by
- Corrected for compatibility with CI v3
- Merge pull request #779 from marcopineschi/patch-1
- Merge pull request #778 from avenirer/patch-8
- Fixes create_user_validation_phone_label error
- More fixes for create_user_validation_phone_label error
- Merge pull request #785 from emilebourquin/2
- Fix default user's password
- Fix markdown
- Merge pull request #787 from kenjis/patch-2
- Merge pull request #786 from kenjis/patch-1
- Update index.html
- Merge pull request #797 from sparky672/patch-5
- updated indonesian language file
- Update ion_auth_lang.php
- Update ion_auth_lang.php
- Merge pull request #803 from suhindra/2
- Update index.html
- Merge pull request #805 from sparky672/patch-6
- Update Ion_auth.php
- Update Ion_auth.php
- Hungarian translation for ion_auth_lang.php
- Update ion_auth_lang.php
- Hungarian translation for auth_lang.php
- Update auth_lang.php
- Update auth_lang.php
- Merge pull request #812 from bbosternak/2
- Merge pull request #809 from sigmoidal/2
- Fix for #804
- Add spaces
- Merge pull request #815 from Tjoosten/Improvements
- Merge pull request #813 from Tjoosten/fix-#804
- #804: fixing missing column type.
- Merge pull request #816 from Tjoosten/patch-1
- convert identation to space
- Merge pull request #817 from marcelod/2
- Updated romanian language file
- Merge pull request #818 from liviuroman/2
- Fixed a bug in logged_in() regarding the userdata index
- Proposal to use any identity column and not username
- changing the model accordingly
- update for identity proposal
- accomodate "identity" proposal into user guide
- update the error calls
- duplicate identity instead of duplicate username
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- Update ion_auth_lang.php
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- Update ion_auth_lang.php
- Merge pull request #824 from makkesk8/patch-1
- Merge pull request #820 from Glowieh/2
- Merge pull request #821 from avenirer/patch-1
- update for identity and not username
- Update auth_lang.php
- Merge pull request #826 from avenirer/patch-2
- to many paranthesys
- not to repeat ourselves...
- Merge pull request #829 from avenirer/patch-5
- Merge pull request #828 from avenirer/patch-4
- Fixes #830 set messages as error
- Merge pull request #832 from ichadhr/2
- Improve if statement
- Merge pull request #836 from Tjoosten/patch-2
- removed redundant code
- Update auth.php
- Update auth.php
- Merge pull request #1 from msadhrao/msadhrao-patch-1
- Input post request name change
- Merge pull request #841 from msadhrao/2
- Merge pull request #842 from BrickGreen/2
- Merge pull request #839 from avenirer/patch-6
- Changes to align with "identity" column
- accomodate "identity" column
- Changes to align with "identity" column
- needs update
- needs update
- needs update
- needs update
- needs update, matey...
- needs update
- needs update
- update for identity proposal
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- needs update
- Merge pull request #847 from avenirer/patch-8
- Update identity translation (indonesian)
- Update identity and action translation
- Merge pull request #854 from suhindra/2
- updated get_attempt_num() to return results by ip address AND identity
  when track_login_ip_address is set to TRUE
- Merge pull request #860 from nplaviola/2
- Update ion_auth_lang.php
- Merge pull request #866 from KasperGreen/patch-1
- set username default as null
- set username default as null
- set username default as null
- Merge pull request #870 from avenirer/patch-8
- more explaining on register() method.
- Merge pull request #873 from avenirer/patch-9
- update traditional chinese translation.
- Merge pull request #882 from appleboy/patch-1
- Fixed issue with errant newline to resolve Issue #865
- resolving identity/email bug
- ... identity/email bug
- Update auth.php
- Update forgot_password.php
- Merge pull request #883 from avenirer/patch-8
- Missing )
- Merge pull request #885 from ponsfrilus/ponsfrilus-patch-1
- new fields translated
- Merge pull request #888 from bbosternak/patch-1
- Converted int castings to floats. Resolves #875;
- translate English into Japanese
- Merge pull request #903 from bootjp/2
- fix #906
- Merge pull request #908 from agung-wete/issue-906
- fix typo
- Merge pull request #912 from suhindra/2
- we remove the posibility of setting 0 as user_id
- Merge pull request #922 from avenirer/patch-9
- Update ion_auth_lang.php
- Merge pull request #923 from HectorFGarcia/patch-1
- ipv6
- Merge pull request #924 from Paradinight/2
- Complete translation
- Complete translation: English -> Polish (updated)
- Merge pull request #925 from vertisan/2
- Renamed files to default to CI3. Updated readme and docs to denote CI2
  compatibility. Updated installation docs for third_party setup instructions.
- Cleaned up docs formatting
- Merge pull request #1 from benedmunds/2
- add docblocks
- Merge pull request #927 from Tjoosten/Tjoosten/Docblocks
- Update auth_lang.php
- Merge pull request #934 from nicolastrognot/patch-1
- Fixed some minor typos
- Update Auth.php
- Merge pull request #939 from enderlinphil/patch-3
- Updated delete_user affected_rows error check to match -1 or 0 due to
  CI DB driver differences
- Fixed some more typos
- Merge pull request #940 from mauriciv/2
- Update german translation
- Update german translation
- Merge pull request #942 from Vmadmax/patch-2
- Merge pull request #941 from Vmadmax/patch-1
- update indonesian translation
- Merge pull request #944 from ichadhr/lang-id
- Added link to Moral License
- Updated lithuanian translations (via Donatas G.)
- Update Ion_auth_model.php
- Merge pull request #951 from zilzurna/2
- Fixing wrong syntax
- Merge pull request #956 from Vmadmax/patch-3
- Added consistency to access modifiers
- Merge pull request #963 from cither1/modifier-consistency
- Removed version number from comments
- Removed version number from comments

File Changes
- _A_ LICENSE
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-0
  (21)
- _D_ README
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-1
  (55)
- _A_ README.md
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-2
  (64)
- _M_ config/ion_auth.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-3
  (318)
- _A_ contributing.md
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-4
  (18)
- _A_ controllers/Auth.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-5
  (819)
- _D_ controllers/auth.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-6
  (389)
- _D_ ion_auth.mssql.sql
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-7
  (56)
- _D_ ion_auth.postgre.sql
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-8
  (52)
- _D_ ion_auth.sql
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-9
  (77)
- _A_ language/arabic/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-10
  (159)
- _M_ language/arabic/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-11
  (75)
- _A_ language/bulgarian/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-12
  (159)
- _A_ language/bulgarian/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-13
  (79)
- _A_ language/catalan/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-14
  (159)
- _M_ language/catalan/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-15
  (54)
- _A_ language/croatian/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-16
  (162)
- _A_ language/croatian/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-17
  (80)
- _A_ language/czech/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-18
  (159)
- _A_ language/czech/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-19
  (75)
- _A_ language/danish/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-20
  (172)
- _A_ language/danish/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-21
  (67)
- _A_ language/dutch/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-22
  (163)
- _M_ language/dutch/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-23
  (52)
- _A_ language/english/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-24
  (144)
- _M_ language/english/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-25
  (89)
- _A_ language/estonian/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-26
  (159)
- _M_ language/estonian/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-27
  (35)
- _A_ language/finnish/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-28
  (159)
- _M_ language/finnish/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-29
  (89)
- _A_ language/french/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-30
  (165)
- _M_ language/french/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-31
  (96)
- _A_ language/german/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-32
  (165)
- _M_ language/german/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-33
  (96)
- _A_ language/greek/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-34
  (159)
- _M_ language/greek/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-35
  (47)
- _A_ language/hungarian/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-36
  (142)
- _A_ language/hungarian/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-37
  (76)
- _A_ language/indonesian/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-38
  (145)
- _A_ language/indonesian/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-39
  (89)
- _A_ language/italian/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-40
  (163)
- _M_ language/italian/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-41
  (44)
- _A_ language/japanese/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-42
  (163)
- _M_ language/japanese/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-43
  (47)
- _A_ language/korean/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-44
  (160)
- _A_ language/korean/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-45
  (77)
- _A_ language/lithuanian/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-46
  (159)
- _A_ language/lithuanian/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-47
  (80)
- _A_ language/norwegian/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-48
  (167)
- _A_ language/norwegian/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-49
  (83)
- _A_ language/persian/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-50
  (159)
- _A_ language/persian/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-51
  (82)
- _A_ language/pirate/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-52
  (159)
- _M_ language/pirate/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-53
  (41)
- _A_ language/polish/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-54
  (161)
- _M_ language/polish/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-55
  (90)
- _A_ language/portuguese/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-56
  (146)
- _M_ language/portuguese/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-57
  (99)
- _A_ language/romanian/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-58
  (141)
- _A_ language/romanian/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-59
  (77)
- _A_ language/russian/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-60
  (165)
- _M_ language/russian/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-61
  (30)
- _A_ language/slovak/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-62
  (159)
- _A_ language/slovak/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-63
  (75)
- _A_ language/slovenian/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-64
  (157)
- _A_ language/slovenian/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-65
  (78)
- _A_ language/spanish/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-66
  (161)
- _M_ language/spanish/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-67
  (93)
- _A_ language/swedish/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-68
  (144)
- _M_ language/swedish/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-69
  (89)
- _A_ language/thai/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-70
  (152)
- _A_ language/thai/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-71
  (83)
- _A_ language/turkish/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-72
  (160)
- _M_ language/turkish/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-73
  (105)
- _A_ language/ukrainian/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-74
  (159)
- _M_ language/ukrainian/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-75
  (32)
- _A_ language/vietnamese/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-76
  (145)
- _A_ language/vietnamese/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-77
  (75)
- _A_ language/zh_cn/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-78
  (165)
- _A_ language/zh_cn/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-79
  (75)
- _A_ language/zh_tw/auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-80
  (150)
- _M_ language/zh_tw/ion_auth_lang.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-81
  (109)
- _A_ libraries/Bcrypt.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-82
  (136)
- _M_ libraries/Ion_auth.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-83
  (832)
- _A_ migrations/001_install_ion_auth.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-84
  (241)
- _A_ models/Ion_auth_model.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-85
  (2249)
- _D_ models/ion_auth_model.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-86
  (1074)
- _A_ sql/ion_auth.mssql.sql
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-87
  (68)
- _A_ sql/ion_auth.postgre.sql
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-88
  (64)
- _A_ sql/ion_auth.sql
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-89
  (95)
- _M_ userguide/index.html
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-90
  (863)
- _M_ views/auth/change_password.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-91
  (29)
- _A_ views/auth/create_group.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-92
  (20)
- _M_ views/auth/create_user.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-93
  (80)
- _M_ views/auth/deactivate_user.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-94
  (35)
- _A_ views/auth/edit_group.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-95
  (20)
- _M_ views/auth/edit_user.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-96
  (87)
- _M_ views/auth/email/activate.tpl.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-97
  (4)
- _M_ views/auth/email/forgot_password.tpl.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-98
  (4)
- _M_ views/auth/email/new_password.tpl.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-99
  (6)
- _M_ views/auth/forgot_password.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-100
  (17)
- _M_ views/auth/index.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-101
  (56)
- _M_ views/auth/login.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-102
  (60)
- _A_ views/auth/reset_password.php
  https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970/files#diff-103
  (22)

Patch Links:
- https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970.patch
- https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/benedmunds/CodeIgniter-Ion-Auth/pull/970, or mute the
thread

**Comment by AsoStrife** [comment]
Yeah, maybe! What would be the right branch?

**Comment by benedmunds** [comment]
The "2" branch

-Ben Edmunds

**Comment by benedmunds** [comment]
Closing due to inactivity

**Pull request closed without merging**
