### PR TITLE
access trigger with remember login

### PR DESCRIPTION
**Pull request by lloricode**
this can be resolve issue #1075 ,

Ive noticed that checking remember is on `contruct`, then i see it also check  `logged_in` ,

so i decide to combine the function `logged_in` and the checking `remember`.

so `ion auth `can load entire file before check if `remeber` login

### CODE REVIEW

**Comment by lloricode** [comment]
also i notice that when `recheck` is FALSE,  it will still login in when using `remember` login,
so it will ignore the `recheck` database function with using `remember` login

**Comment by benedmunds** [comment]
Idea of the changes look good.  Do you need that is_bool check though?  From what I see the function always returns a bool...

**Comment by lloricode** [comment]
the return of `recheck_session` has a two of FALSE either `session` is expire OR the user detect `inactive`.

so maybe need to identify what mean of FALSE returned by a function.


to prevent using remember login event the user is inactive.


hmmm im not sure the change maybe it need more enhance. im still confusing here

**Comment by lloricode** [comment]
hmm sir @benedmunds , can you test it? or improve it?

**Comment by benedmunds** [comment]
Hey,

I'm just going to close this PR.  I'm all for making things more efficient but not at the detriment of clarity and backwards compatibility.

1.  I think the new logic for the controller is harder to follow.

2.  I don't want to change the current functionality of the model method because users may be expecting it to work as is and this change has the risk of breaking backwards compatibility.


Thanks so much for the contribution though and take care!

**Comment by lloricode** [comment]
yes the compatibility is important,
thanks @benedmunds  :)

**Comment by lloricode** [comment]
hi @benedmunds , can I PR only fiirst commit ? it should be first load entire library before check the remember.

**Comment by benedmunds** [comment]
Still not sure how I feel about this.  There is nothing forcing the logged_in() method call so it seems like this may still break BC for some users.

@avenirer do you have an opinion here?

**Comment by avenirer** [comment]
I am sorry @lloricode @benedmunds . I would have to look at it in the following days, if you have time to wait :(

**Comment by lloricode** [comment]
@benedmunds maybe @avenirer has much idea, so we can wait :)

**Pull request closed without merging**
