### PR TITLE
Use salt prefix based on PHP_VERSION

### PR DESCRIPTION
**Pull request by andrefrcastro**

### CODE REVIEW

**Comment by benedmunds** [comment]
Can you add the correct default password hash to the config in a comment as well for each

**Comment by andrefrcastro** [comment]
The word 'password' gave me this:

$2y$ : $2y$08$ShvdrBDBsaUpCgUV0uztF.kqLtBku6fNOZlrrTEVTB0MwWMsjoMJK
$2a$ : $2a$08$Qg5eNYIEDr/PGqEEQc/k5uIYb9PPwNIoVtB337T1MQp4.SI63M5Pm

Is this correct? 
It doesnt match with yours ($2a$07$SeBknntpZror9uyftVopmu61qg0ms8Qv1yV6FG.kQOSM.9QhmTo36)

**Comment by benedmunds** [comment]
same rounds as the config default?

**Comment by andrefrcastro** [comment]
Yes, i didnt change my config settings for hashing:

```php
$config['hash_method']    = 'bcrypt';	// sha1 or bcrypt, bcrypt is STRONGLY recommended
$config['default_rounds'] = 8;		// This does not apply if random_rounds is set to true
$config['random_rounds']  = FALSE;
$config['min_rounds']     = 5;
$config['max_rounds']     = 9;
$config['salt_prefix']    = version_compare(PHP_VERSION, '5.3.7', '<') ? '$2a$' : '$2y$';
```

Can you provide me the hashed values for 'password' and i'll put them in the comments ?

Thanks.

**Comment by benedmunds** [comment]
I'm getting:

$2y$:  $2y$08$200Z6ZZbp3RAEXoaWcMA6uJOFicwNZaqk4oDhqTUiFXFe63MG.Daa

$2a$:  $2a$08$6TTcWD1CJ8pzDy.2U3mdi.tpl.nYOR1pwYXwblZdyQd9SL16B7Cqa


but you have to keep in mind that it has a random salt with each new hash so they wont match.  So yours should be fine.

**Comment by andrefrcastro** [comment]
Im ok with it, it's just because you asked to add hashed values for password in the comments.

**Comment by benedmunds** [comment]
Thanks!

**Pull request merged**
