### PR TITLE
Add composer.json for 3

### PR DESCRIPTION
**Pull request by kenjis**
I just want to install the latest Ion Auth 3 with Composer like this:

```
$ composer require benedmunds/codeigniter-ion-auth:3.x-dev
```

But there is no `composer.json`, so I can't do it.

### CODE REVIEW

**Comment by benedmunds** [comment]
Does this work with CI3’s loader? Or are you having to add a MyLoader on top?

**Comment by kenjis** [comment]
> Does this work with CI3’s loader?

No. 

With this we can just install Ion Auth in `vender` folder. So there is no way to load by
CI_Loader. We need to copy files to `application` folder like <https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/3/INSTALLING.md#installing-ion-auth>.

But I'm going to add Composer [command events](https://getcomposer.org/doc/articles/scripts.md#command-events) `post-install-cmd` `post-update-cmd` in my `composer.json`, which copies Ion Auth files (in `vender`)  into my `application` folder (like `application/libraries/Ion_auth.php`). 

So I can use the latest Ion Auth files just to run `composer update`.

**Comment by benedmunds** [comment]
Ok cool. Lmk once those commands are in place and I’ll test/merge.  Thanks!

**Comment by kenjis** [comment]
@benedmunds I added sample `scripts` in the `composer.json` in this PR.

You can test it with my repository (`git@github.com:kenjis/CodeIgniter-Ion-Auth.git`):

1. Install CI3 as you like.

```
$ composer create-project kenjis/codeigniter-composer-installer ci3
```

2. Edit your project `composer.json`.

```
$ cd ci3
$ vi composer.json
```

```diff
--- a/composer.json
+++ b/composer.json
@@ -6,5 +6,34 @@
        },
        "require-dev": {
                "mikey179/vfsStream": "1.1.*"
+       },
+       "repositories": [
+               {
+                       "type": "vcs",
+                       "url": "git@github.com:kenjis/CodeIgniter-Ion-Auth.git"
+               }
+       ],
+       "scripts": {
+               "install-ion-auth": [
+                       "[ -f application/config/ion_auth.php ] || cp -p vendor/benedmunds/codeigniter-ion-auth/config/ion_auth.php application/config/",
+                       "@install-ion-auth-clm",
+                       "[ -d application/views/auth ] || cp -pr vendor/benedmunds/codeigniter-ion-auth/views/* application/views/"
+               ],
+               "force-install-ion-auth": [
+                       "cp -p vendor/benedmunds/codeigniter-ion-auth/config/ion_auth.php application/config/",
+                       "@install-ion-auth-clm",
+                       "cp -pr vendor/benedmunds/codeigniter-ion-auth/views/* application/views/"
+               ],
+               "install-ion-auth-clm": [
+                       "cp -p vendor/benedmunds/codeigniter-ion-auth/controllers/Auth.php application/controllers/",
+                       "cp -p vendor/benedmunds/codeigniter-ion-auth/libraries/Ion_auth.php application/libraries/",
+                       "cp -p vendor/benedmunds/codeigniter-ion-auth/models/Ion_auth_model.php application/models/"
+               ],
+               "post-install-cmd": [
+                       "@install-ion-auth"
+               ],
+               "post-update-cmd": [
+                       "@install-ion-auth"
+               ]
        }
 }
```

3. Install Ion Auth.

```
$ composer require benedmunds/codeigniter-ion-auth:3.x-dev
```

```
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)                                                    
Package operations: 1 install, 0 updates, 0 removals
  - Installing benedmunds/codeigniter-ion-auth (3.x-dev 1547363): Cloning 1547363d8e from cache
Writing lock file
Generating autoload files
> [ -f application/config/ion_auth.php ] || cp -p vendor/benedmunds/codeigniter-ion-auth/config/ion_auth.php application/config/
> cp -p vendor/benedmunds/codeigniter-ion-auth/controllers/Auth.php application/controllers/
> cp -p vendor/benedmunds/codeigniter-ion-auth/libraries/Ion_auth.php application/libraries/
> cp -p vendor/benedmunds/codeigniter-ion-auth/models/Ion_auth_model.php application/models/
> [ -d application/views/auth ] || cp -pr vendor/benedmunds/codeigniter-ion-auth/views/* application/views/
```

**Comment by benedmunds** [comment]
Awesome.  A couple changes.

I see that you set the config to not overwrite.  Can you do the same for the controller and views.  Most users will have application specific changes here.

Also what is the "force-install-ion-auth" command for? I don't see it used here.

**Comment by kenjis** [comment]
@benedmunds 
I've changed it as not to overwrite the controller.

The views are not copied if `application/views/auth` exists.

I removed  "force-install-ion-auth" command, because it has no use cases for most users.

**Comment by benedmunds** [comment]
Thanks so much!

**Pull request merged**
