### PR TITLE
Only use IP if track_login_ip_address is set

### PR DESCRIPTION
**Pull request by Indigo744**
The functions `increase_login_attempts()` and `clear_login_attempts()` made use of the IP address, independently of the `track_login_ip_address` configuration value.

So we make sure that the setting is correctly used.

### CODE REVIEW

**Comment by benedmunds** [comment]
I think we'd want to store the IP in the attempts table either way.  Then just not use it if it's not setup for it.

It doesnt hurt to track it and it comes in handy for troubleshooting in my experience.

Thoughts?

**Comment by Indigo744** [comment]
I would tend to agree. However, there are some laws (like the European data protection law) which forbid to store any user information if he hasn't explicitly agreed to.

I know this is far-fetched in some case, but if the dev don't want the IP to be tracked at login attempts, why should we do it anyway?

This is also to be consistent with the other functions...

**Comment by benedmunds** [comment]
Yea I can see your point there.  Who knows how those laws will change in the future either 😱

**Comment by benedmunds** [comment]
Merging

**Comment by avenirer** [comment]
Security centric cookies are clearly exempt from consent according to the EU advisory body on data protection- WP29. (http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm)

**Pull request merged**
