### PR TITLE
Ion Auth 3 : cleanup unused functions

### PR DESCRIPTION
**Pull request by Indigo744**
Related to #1195

Some functions were kept for BC. They should be removed.

1. Function `forgotten_password_complete()` doesn't seem to be used anymore, and has a security issue since the password is sent by mail in clear text (see #872) 
2. Function `_prepare_ip()`: the doc says it is only kept for BC
3. Function `is_time_locked_out()`: doc says it is only a wrapper for `is_max_login_attempts_excedeed()`

Do you see any other functions to remove?

### CODE REVIEW

**Comment by benedmunds** [comment]
Good stuff, I love seeing old code removed.  I don't see anything else that should be removed.  

Can you updated the PR to be agains the 3 branch.

**Comment by Indigo744** [comment]
Done 😺

**Comment by benedmunds** [comment]
Still looks like its against the 2 branch 
screen shot 2018-03-20 at 10 49 38 am

**Comment by Indigo744** [comment]
Oh damn sorry!

**Comment by benedmunds** [comment]
No problem! Thanks

**Pull request merged**
