### PR TITLE
HOTFIX - #1403

### LINKED ISSUE #1403: Change password not working v4
# Hotifx 

## In the branch ci4, the method change_password is not working. This generates by the new structure of CI4

file Controller/Auth, line number 248

file Model/Ion_auth_model, method `change_password`

### PR DESCRIPTION
**Pull request by Daniel-Monroy**
It is resolved #1403

### CODE REVIEW

**Comment by benedmunds** [comment]
Are these model changes needed as well even though they aren’t related to the session data?

**Comment by Daniel-Monroy** [comment]
Yes, otherwise it produces an error

**Comment by benedmunds** [comment]
Thanks!

**Comment by Daniel-Monroy** [comment]
You're welcome, thanks for the great library Ben

**Comment by benedmunds** [comment]
Thanks for the help!  Are you seeing any other issues? It looks like the other queries might need to change to use the builder structure as well.

**Comment by Daniel-Monroy** [comment]
We are starting with CI4, if we had new problems as soon as possible, we
notified

**Comment by benedmunds** [comment]
Thanks so much!

**Pull request merged**
