### PR TITLE
Add get_all_attempts() function to model

### PR DESCRIPTION
**Pull request by Indigo744**
I needed this function from a manager point of view (my client wanted to be able to look at all attempts in one place).

This function will return an array populated with all useful information regarding attemps (see list in comments). I used the same key names as existing function:
- 'attempts_num' refers to function `get_attempts_num()`
- 'last_attempt_time' refers to function `get_last_attempt_time()`
- 'is_time_locked_out' refers to function `is_time_locked_out()`

### CODE REVIEW

**Comment by benedmunds** [comment]
I'm going to close this PR without merging.  Not because there are any issues with it, just because i don't believe it will have wide spread enough need to justify adding it to the core API.  I will be happy to point people here if anyone needs it going forward.  Thanks!

**Comment by Indigo744** [comment]
Aww.. Ok, I understand..
Quick question git/github related: if I ever delete this branch, will this stay as is?

**Comment by benedmunds** [comment]
I'm actually not sure..

**Comment by Indigo744** [comment]
I just deleted the branch, and the commit and modifed files are still visible. Good!

**Comment by benedmunds** [comment]
👍 👍 👍   Thanks!

**Pull request closed without merging**
