### PR TITLE
Some lines missing in English lang file

### PR DESCRIPTION
**Pull request by duub**
I found that in the english file those lines were missing

### CODE REVIEW

**Comment by avenirer** [comment]
Most likely they are missing because they are no longer in use by the library. The English language files should always be considered the template for the other language files and not the other way around.

**Comment by duub** [comment]
Ok! I didn't know that. I have been translating into catalan, so you are saying that instead of adding into English I should remove it from the catalan file? The english version is the one it is updated?

**Comment by benedmunds** [comment]
@duub yea that's correct, the english version has been updated most likely.

**Comment by duub** [comment]
Ok! then We can discard the PR

**Pull request closed without merging**
