### PR TITLE
Update Ion_auth_model.php

### PR DESCRIPTION
**Pull request by zilzurna**
#949

### CODE REVIEW

**Comment by benedmunds** [comment]
Should this also have a limit of 1?

**Comment by zilzurna** [comment]
@benedmunds  It already has limit 1.

$this->db->get($this->tables['login_attempts'], **1**)

**Comment by benedmunds** [comment]
Yup you're right.  Merging.  Thanks!!

**Comment by zilzurna** [comment]
Thank you!

**Pull request merged**
