### PR TITLE
Fix remember me

### PR DESCRIPTION
**Pull request by abitme**
fix remember me, when cookie destroyed after redirect, fix query in loginRememberedUser function, and fix cookie when logout

### CODE REVIEW

**Comment by benedmunds** [comment]
Hey,

Did you find another solution to this?

**Comment by abitme** [comment]
> Hey,
> 
> Did you find another solution to this?

Yeah, There's something that i have to add. I have sent my new pull request, please check it. hopefully it should works fine

**Comment by benedmunds** [comment]
Ah ok thanks!

**Comment by abitme** [comment]
I make new commit that keep $this->identityColumn in clearRememberCode function to avoid error when user doesn't use remember me

**Pull request closed without merging**
