### PR TITLE
forgot password issue when identity is USERNAME

### PR DESCRIPTION
**Pull request by lloricode**
fix when the user identity is USERNAME, then forgot password will still use EMAIL

### CODE REVIEW

**Comment by lloricode** [comment]
I use this in my thesis project

http://ci-capstone.lloricmayugagarcia.com/

my repo:
https://github.com/lloricode/ci-capstone

hmmm I hope will help

i modify the ion_auth to work mine

thanks.

**Comment by benedmunds** [comment]
Im not sure I see why you made these changes. Can you explain the error you saw?  and can you post your ion auth config file contents.

**Comment by lloricode** [comment]
**ion_auth.php line:  89**
`$config['identity']                   = 'username';  `

[ion_auth.php](https://github.com/lloricode/ci-capstone/blob/version2/application/config/ion_auth.php)

because my login is uses username not email, hmmm

**Comment by benedmunds** [comment]
I don't see an issue with that. What error did you run into?

**Comment by lloricode** [comment]
when user use forgot password, that forgot password code is will send in user email,
then in my `$config['identity']`  I set ` 'username'` beacuase my login is only uses **username**.

my problem is, when user use forgot password, it cannot send email even `$config['use_ci_email'] = TRUE;` beause the `$identity` will use is username also not email, 

the ion_auth will send email, but cant because it only search username for user.

**Comment by lloricode** [comment]
no need to set dynamically the `identy` when use forgot password, because forgot password uses only email identity to send code on exist email from user who just request a forgot password code

**Comment by avenirer** [comment]
@lloricode Looking at the code you've changed, I see that there are lines changed that are not really changed. Please, redo the pull request and only change what you want to change. Don't just redo entire blocks of code that are not changed at all, just for a line or two. @benedmunds I wouldn't merge the PR, because I really don't see what was changed (I only see a line changed, but I don't know if this is right).

**Comment by lloricode** [comment]
@avenirer hmm thanks for respone, i will PR later

**Comment by lloricode** [comment]
#1035 
 i re-forked a repo

**Comment by avenirer** [comment]
Most likely the problem is with the email setup. Are you receiving emails from the library in all the other cases? You didn't tell us what error was shown.

**Comment by lloricode** [comment]
i did not receive any email, just return `##forgot_password_identity_not_found##`, 

as i also observe is i was set `$identity` to `'username'`, then when i see the ion_auth is when sending request code is the identity is using , that i set username

**Comment by benedmunds** [comment]
You are wanting to use the username as the identify correct?

Are you receiving the email? At what step do you receive this error?  Screenshots and code examples from your controller will be very helpful in diagnosing the issue.


And like @avenirer asked, are you receiving email from other functions?

**Comment by lloricode** [comment]
omg now is no more issue, hmm now its work fine.
@avenirer now i see the my mistake, its my faultt , hmm
@benedmunds this is the code i fix in mine. 

now i fully understand why you did not accept my PR, thanks guys for the idea. i will help others and introduce this library.

im being stress with this now next problem, im working on my thesism and i will use this when im work,

```
        public function forgot_password()
        {
                // setting validation rules by checking whether identity is username or email
                if ($this->config->item('identity', 'ion_auth') != 'email')
                {
                        $this->form_validation->set_rules('identity', $this->lang->line('forgot_password_identity_label'), 'required');
                }
                else
                {
                        $this->form_validation->set_rules('identity', $this->lang->line('forgot_password_validation_email_label'), 'required|valid_email');
                }


                if ($this->form_validation->run() == false)
                {

                        $this->set_data();
                        $this->_render_page('admin/login', $this->data);
                }
                else
                {
                        $identity_column = $this->config->item('identity', 'ion_auth');
                        $identity        = $this->ion_auth->where($identity_column, $this->input->post('identity'))->users()->row();

                        if (empty($identity))
                        {

                                if ($this->config->item('identity', 'ion_auth') != 'email')
                                {
                                        $this->ion_auth->set_error('forgot_password_identity_not_found');
                                }
                                else
                                {
                                        $this->ion_auth->set_error('forgot_password_email_not_found');
                                }

                                $this->session->set_flashdata('message', $this->ion_auth->errors());
                                redirect("admin/auth/login", 'refresh');
                        }

                        // run the forgotten password method to email an activation code to the user
                        ///////////////////////////////////////////////////////////////////////////////////    
                        ///////////////////////////////////////////////////////////////////////////////////    
                        ///////////////////////////////////////////////////////////////////////////////////    
                        ///////////////////////////////////////////////////////////////////////////////////    
                        ///////////////////////////////////////////////////////////////////////////////////    
                        ///////////////////////////////////////////////////////////////////////////////////
                       
                        //this is my issue
                        $forgotten = $this->ion_auth->forgotten_password($identity->email);

                        //the i fix now, this is my mistake
                        $forgotten = $this->ion_auth->forgotten_password($identity->{$this->config->item('identity', 'ion_auth')});


                        ///////////////////////////////////////////////////////////////////////////////////    
                        ///////////////////////////////////////////////////////////////////////////////////   
                        ///////////////////////////////////////////////////////////////////////////////////    
                        ///////////////////////////////////////////////////////////////////////////////////   
                        ///////////////////////////////////////////////////////////////////////////////////    
                        ///////////////////////////////////////////////////////////////////////////////////   
                        ///////////////////////////////////////////////////////////////////////////////////    
                        ///////////////////////////////////////////////////////////////////////////////////    
                        ///////////////////////////////////////////////////////////////////////////////////

                        if ($forgotten)
                        {
                                // if there were no errors
                                $this->session->set_flashdata('message', $this->ion_auth->messages());
                                redirect("admin/auth/login", 'refresh'); //we should display a confirmation page here instead of the login page
                        }
                        else
                        {
                                $this->session->set_flashdata('message', $this->ion_auth->errors());
                                redirect("admin/auth/login", 'refresh');
                        }
                }
        }
```

**Comment by avenirer** [comment]
@lloricode Hello. Did you manage to look into it? What I've found out is that, because the email is not sent, that error message appears. That is because inside the library file, if $this->mail->send() ends with false value (libraries/Ion_auth.php lines 171-177), then the "reset_password_unsuccessful" (which translates to "Failed to reset password") is outputted. This means that the problem is with sending emails. Try to send an email from inside your CI app and see if it works.

**Comment by lloricode** [comment]
@avenirer did ou mean is `forgot_password_unsuccessful`?

screenshot at 2017-02-07 06-43-43

hmm it works

**Pull request closed without merging**
