### PR TITLE
Update userguide

### PR DESCRIPTION
**Pull request by Tjoosten**

### CODE REVIEW

**Comment by benedmunds** [comment]
CI v2 uses the v2 style CI docs.  For now I think I'd like to keep it that way since that will be most familiar to the users.

Anyone else have any thoughts on this vs the old style docs?

**Comment by Tjoosten** [comment]
i think this one is better. because you can maintain you documentation in the code

**Comment by tlagard** [comment]
I say leave it this way for now but let everyone know that it will probably change in the future.

**Comment by avenirer** [comment]
Changing the design of the userguide would be a no from me. I actually don't like how the CI3 manual looks. I liked better the v2 one.

Spaces in code would be a yes from me.

**Comment by Tjoosten** [comment]
@avenirer you got a point there

**Comment by benedmunds** [comment]
Closing for now.  We'll go to a new style for Ion Auth v3 though.

**Pull request closed without merging**
