### PR TITLE
recheck session against database after some defined time

### PR DESCRIPTION
**Pull request by avenirer**
as per issue #1045, it seems like a good idea... It is a proposal, so it can be repelled.

### CODE REVIEW

**Comment by benedmunds** [comment]
I like this idea!

**Comment by benedmunds** [comment]
Just let me know when the PR is ready for review, looks like it's still in active dev atm

**Comment by avenirer** [comment]
@benedmunds ready...

**Comment by avenirer** [comment]
it should be backwards compatible...

**Comment by benedmunds** [comment]
Walk me through.  The plan is to recheck their session if they logged in longer than X seconds ago?

**Comment by avenirer** [comment]
1. check if the user has set up a recheck_timer
2. if it did, when method logged_in() is called, the recheck_session() method from ion_auth_model is called
3. in recheck_session() we check if the current time plus the recheck_timer in seconds is smaller than current time. if that's the case then the user is verified against database. if the user doesn't exist or it is inactive, the session data is unset and the method returns false. Else, the session data 'last_login' is reset to current time() and the method returns true.
4. true/false (what is returned from recheck_session()) is then returned from logged_in().

**Comment by benedmunds** [comment]
Makes sense.  Couple things:

1. How about we change the default in the config to something like ~5 min.  I want to promote a performant default here.

2. What do you think about renaming last_login to something else? Since its more like a last_modified or last_update or something rather than last_login...

**Comment by avenirer** [comment]
1. I would rather leave it to zero and let the users decide (maybe mention "if you really think you need to recheck the session against database, we would recommend a higher value, as this would affect performance" in the comment). If it's set to zero, the session won't be rechecked.
2. that would be a great idea... maybe "last_check"?

**Comment by benedmunds** [comment]
@avenirer 1 - yup that sounds great.  2 - agreed, works for me.

**Comment by benedmunds** [comment]
Oh one other thing.  is there any need to do the full query instead of just $this->user()?

**Comment by avenirer** [comment]
$this->user() would return quite some data, just like the query I've done in there... which is a lot and not needed... So I only asked for id now. It's more than enough to return us one row.

**Comment by benedmunds** [comment]
Looks great, thanks man.  Merging!

**Review by lloricode — COMMENTED** [review]
more secure :)

**Pull request merged**
