### PR TITLE
Add Seed file

### PR DESCRIPTION
**Pull request by bvrignaud**
Add seed file and remove datas from migration files.
Update doc to.

### CODE REVIEW

**Comment by tpw1314** [comment]
One question. In your documentation, you use php spark command in installation section. I am unable to find much information about Spark. Does it work the same if I just use composer ?
I think it will be better if you just add another line or two for alternate option. @bvrignaud

**Comment by benedmunds** [comment]
Wouldn’t hurt to remove Spark info, it’s bit outdated at this point

**Comment by tpw1314** [comment]
Thanks for your response. Anyway what can you replace it with ? Like laravel we can simply use php artisan migrate

**Comment by bvrignaud** [comment]
Spark is the CodeIgniter CLI tool as artisan for Laravel : https://codeigniter4.github.io/CodeIgniter4/cli/cli_commands.html?highlight=spark
https://codeigniter4.github.io/CodeIgniter4/dbmgmt/seeds.html

**Comment by tpw1314** [comment]
weird. I am unable to run php spark. In my case, it simply say "Could not open input file".

**Comment by bvrignaud** [comment]
Wich CI4 version do you use ?

**Comment by tpw1314** [comment]
currently fresh from develop - Release v4.0.0-alpha.3

**Comment by benedmunds** [comment]
Oh my bad, didn’t realize this was referencing the 4 branch.  Spark was also the name of an old CodeIgniter dependency management tool. Carry on :)

**Comment by tpw1314** [comment]
@bvrignaud my bad. Sovled the problem by re-checking out root directory. Was missing spark file. @benedmunds Thanks.

**Comment by bvrignaud** [comment]
Glad to read that.

**Comment by tpw1314** [comment]
php spark db:seed IonAuth\\Database\\Seeds\\IonAuthSeeder << Cant get it running even after I remove 'IonAuth'. Should not I just run php spark db:seed if you already namespace IonAuth\Database\Seeds ?

**Comment by bvrignaud** [comment]
There was errors in IonAUthSeeder.
I resolved them.
#1294

**Comment by tpw1314** [comment]
@benedmunds please pull and merge these fixes, thank you. Can't wait to test IonAuthSeeder. I am fired up to merge with my apps yay.

**Comment by benedmunds** [comment]
Merged 🎉

**Comment by tpw1314** [comment]
hi there. Still class not found when `php spark db:seed IonAuth\\\Database\\\Seeds\\\IonAuthSeeder` is run. I tried a little debugging based on CI4 docs, seems like a namespace issue.
~~[CI4 doc part](https://codeigniter4.github.io/CodeIgniter4/general/configuration.html?highlight=config#accessing-config-files)~~
~~Config\\\IonAuth or IonAuth\\\Config\\\IonAuth ? Tried both and still no avail.~~
class not found so above line definitely not the case.
- `C:\xampp\htdocs\CI4\CodeIgniter4\application\Database/Seeds/IonAuth\\Database\\Seeds\\IonAuthSeeder.php`
Is it just me or there is something weird about this seed path ?

[Tried this too](https://codeigniter4.github.io/CodeIgniter4/general/modules.html?highlight=config#seeds)
`php public/index.php migrations seed IonAuth\\Database\\Seeds\\IonAuthSeeder`
Controller or Method not found. Path issue? Or CI4 issue ?

**Comment by bvrignaud** [comment]
1) Which CI version do you use ? I use the develop from yesterday.
2) Where do you run spark ? It must be run inside you CI4 folder (C:\xampp\htdocs\CI4\CodeIgniter4\)
3) Does `php spark` return something ?
4) Your cmd is strange. Why 3 '\' instead of 2 : `php spark db:seed IonAuth\\Database\\Seeds\\IonAuthSeeder`

**Comment by tpw1314** [comment]
1. I forked my own branch and merged with latest develop. My changes were only `public $enabled = true;` in Config\\Migration file
2. Yes Same directory.
3. `An uncaught Exception was encountered
Type:        Error
Message:     Class 'IonAuth\\Database\\Seeds\\IonAuthSeeder' not found
Filename:    C:\xampp\htdocs\CI4\CodeIgniter4\system\Database\Seeder.php
Line Number: 145`

`Backtrace:
                        -122 - C:\xampp\htdocs\CI4\CodeIgniter4\system\Commands\Database\Seed.php::call`
4. sorry just now was not using code tag so that '\' got escaped by Github, that is why I added extra backslash.

**Comment by bvrignaud** [comment]
Have you, add this, in your Config/Autoload.php :

'IonAuth' => ROOTPATH . 'CodeIgniter-Ion-Auth',

**Comment by bvrignaud** [comment]
3) just run `php spark` without params.

**Comment by tpw1314** [comment]
Added. the path is suppose to be the ionauth controller ?
` Namespace   | Path                                                | Found?  |`
`+-------------+-----------------------------------------------------+---------+`
`| CodeIgniter | C:\xampp\htdocs\CI4\CodeIgniter4\system             | Yes     |`
`| Config      | C:\xampp\htdocs\CI4\CodeIgniter4\application\Config | Yes     |`
`| App         | C:\xampp\htdocs\CI4\CodeIgniter4\application        | Yes     |`
`| IonAuth     | C:\xampp\htdocs\CI4\CodeIgniter4\public             | MISSING`

**Comment by bvrignaud** [comment]
No, the path must be the main IonAuth folder path.
In my project, I have : `ROOTPATH . 'CodeIgniter-Ion-Auth',`

**Comment by tpw1314** [comment]
Suppose I have CodeIgniter4 (main CI4 framwork) folder, I downloaded CodeIgniter-Ion-Auth zip and unzip everything and replace in CodeIgniter4/application folder.
Is my root folder of IonAuth now C:\xampp\htdocs\CI4\CodeIgniter4\application ?
Or is CI4 now supports explicit folder structure where I can place CI4 library outside of CodeIgniter4 fodler ?

**Comment by bvrignaud** [comment]
CI4 support now modules : https://codeigniter4.github.io/CodeIgniter4/general/modules.html
As the doc (https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/4/INSTALLING.md) said (Installing Ion Auth - 3), you have to copy your unzip folder in CI4 root.
So, on your example, you must have something like this :
C:\xampp\htdocs\CI4\CodeIgniter4\CodeIgniter-Ion-Auth

**Comment by tpw1314** [comment]
totally missed out this part.... Will implement these and try again. Thanks for pointing out.

**Comment by tpw1314** [comment]
`$psr4 = [
'IonAuth' => ROOTPATH.'ion4'
];`
My folder name is ion4, folder structure is following module (CodeIgniter/ion4).
ran `php spark migrate:latest -n IonAuth` and no issue, success.
However, `php spark db:seed IonAuth\\Database\\Seeds\\IonAuthSeeder` still gives me :
`Class 'IonAuth\\Database\\Seeds\\IonAuthSeeder' not found`.

Am I still missing something despite following this [guide here](https://github.com/benedmunds/CodeIgniter-Ion-Auth/blob/4/INSTALLING.md) ?

**Comment by tpw1314** [comment]
Nvm solved it. How do I make contribution ? I would like to amend documentation especially INSTALLING.md.

**Pull request merged**
