### PR TITLE
Changes to align with "identity" column

### PR DESCRIPTION
**Pull request by avenirer**
This and the following changes are required in order to accommodate with the "identity" column

### CODE REVIEW

**Comment by avenirer** [comment]
This is for the creation of users...

**Comment by benedmunds** [comment]
Looks good. Can you add the new var to the rest of the language files as well, just make the text english as well.

**Comment by avenirer** [comment]
The translation part is by far the hardest one...

**Comment by benedmunds** [comment]
Ha ikr!  Thanks!!!

**Pull request merged**
