### PR TITLE
Adds Documentation as Markdown

### PR DESCRIPTION
**Pull request by iAdesanyaDaniel**
Credit to [Cloud Convert](https://cloudconvert.com/html-to-md).

The service did a nice job. I only had to work on the 'Table of content' and the 'Code formating'

### CODE REVIEW

**Comment by benedmunds** [comment]
This is awesome!  Great work here, if you get time I'd love to have the same thing for the 4 branch.

**Comment by iAdesanyaDaniel** [comment]
Thank you for the kind words, and the warm welcome.

I will definitely check Branch 4 out, but I would like to know if the user guide is identical to the one for Branch 3?

**Comment by benedmunds** [comment]
The layout is similar but the content is different.

**Comment by iAdesanyaDaniel** [comment]
Ok. I would work on it once I'm free.
Thanks a lot.

**Comment by benedmunds** [comment]
Awesome, thank you!

**Pull request merged**
