### PR TITLE
Proposal to use any identity column and not username

### PR DESCRIPTION
**Pull request by avenirer**
This will allow users to use any field as identity column, and not only "username" (As per issue #819 ).

### CODE REVIEW

**Comment by avenirer** [comment]
If @benedmunds will merge this, I will also update the language files in english, and the controller (maybe also the user guide...)

**Comment by benedmunds** [comment]
This is a great change.  Can you update the docs and lang files in this same PR?

**Comment by avenirer** [comment]
@benedmunds I sure hope I didn't miss anything...

**Comment by benedmunds** [comment]
THANK YOU!!!

**Pull request merged**
