### PR TITLE
OTP integration

### PR DESCRIPTION
**Pull request by biscofil**
from https://github.com/SpyTec/CodeIgniter-Ion-Auth-OTP

### CODE REVIEW

**Comment by benedmunds** [comment]
This looks awesome.

I'm not sure if this is a good fit for the main repo/branch though since it's not something most users will use.  What do you think if I create a new "otp" branch for it?

**Comment by biscofil** [comment]
That would be great!

**Comment by benedmunds** [comment]
Branch created and added a link to the readme on the 2 branch.  Thanks so much!

https://github.com/benedmunds/CodeIgniter-Ion-Auth/tree/otp

**Comment by biscofil** [comment]
Thanks to you!

**Pull request closed without merging**
