### PR TITLE
Modify forgot_password_identity_label

### PR DESCRIPTION
**Pull request by orbitasol**

### CODE REVIEW

**Comment by benedmunds** [comment]
Awesome, thank you!

Can you remove the formatting changes from this PR? That’s separate from the language changes and it’s not in line with the CI style for CI v3.

**Comment by orbitasol** [comment]
Hi sir, i will really appreciate to remove the formatting changes from the PR, unfortunately i don't know how i can can do this as i'm new on git and github. Could you indicate me how i can do it?

**Comment by benedmunds** [comment]
The easiest way is probably to submit a new PR and only commit changes to the language files in that branch.

**Comment by benedmunds** [comment]
Closing this due to inactivity, feel free to reopen when an update is ready.

**Pull request closed without merging**
