### PR TITLE
remove dynamically identity in requesting forgot password code

### PR DESCRIPTION
**Pull request by lloricode**
only user_email will parameter in two functions

```
$this->ion_auth->forgotten_passwor($user_email);
$this->ion_auth_model->forgotten_password($user_email);
```

### CODE REVIEW

**Comment by lloricode** [comment]
@avenirer i hope is this ok,

**Comment by avenirer** [comment]
@lloricode @benedmunds I really don't understand the reason for doing this change. This is not doing anything new. It is only adding a new unnecessary config item. Instead of letting the library take the email address from the user row, it takes the configuration column for email to retrieve it.

**Comment by lloricode** [comment]
@avenirer  hmm much better.  in two file i just set email even identity is username

**Comment by avenirer** [comment]
@lloricode But that is just what I tell you. The model is already taking the email field from the user result. There is no need for these changes.

**Comment by lloricode** [comment]
@avenirer  I understand. maybe my usage/flow is the problem, by the way thanks, now i have idea to use to solve my issue.

**Comment by lloricode** [comment]
hmm im still confusing

**Comment by benedmunds** [comment]
I'm not following either. The user record is queried by the identity and then the email is used from the user record

**Pull request closed without merging**
