### PR TITLE
Update: Possibility of changing the column names easily

### PR DESCRIPTION
**Pull request by LuanBaviloni**
Implementation of the possibility of changing the column names of tables.

### CODE REVIEW

**Comment by benedmunds** [comment]
Can some people thumbs up or down this based on if they would use this functionality?  

I’ve only seen one or two people ask for this over the years that I remember...

**Comment by ghosthouse** [comment]
Yes would like that option very much.

**Comment by avenirer** [comment]
Then, maybe, the next thing would be to also give the possibility to change the name of the tables... I guess this is getting out of hand. :)

**Comment by LuanBaviloni** [comment]
It's useful when you have to follow specific naming patterns/conventions in database modeling.

**Comment by paklie** [comment]
thumbs up..

**Comment by benedmunds** [comment]
Closing this PR since we didn't get overwhelming votes for it and it's not worth the added complexity imho.  If you want to submit a similar PR against the v4 branch, or just commenting and getting @bvrignaud 's thoughts in #1273 I would consider implementing it there since it'l be a fresh release.

**Pull request closed without merging**
