### PR TITLE
Add message logging in case email failed

### PR DESCRIPTION
**Pull request by trungdq88**

### CODE REVIEW

**Comment by avenirer** [comment]
This is a particular case. I wouldn't merge.

**Comment by benedmunds** [comment]
If you're up for adding this to each failed email send, along with a note of the location, like "ion_auth_register", for each then I'd love to merge it

**Comment by trungdq88** [comment]
@benedmunds, @avenirer sorry for this. I will have a look at each email send and push new commits later.

**Comment by benedmunds** [comment]
Closing due to being stale.

**Pull request closed without merging**
